name: Generate Snake

on:
  schedule: # executa o workflow a cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2.1.0
        with:
          github_user_name: viniciusbarbosa2024
          outputs: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
      - name: Atualizar o README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Atualizando gráfico de contribuições"
          git push
